[project]
name = "ssl_simulator"
version = "0.0.1"
description = "Swarm Systems Lab Python Simulator"
readme = "README.md"
requires-python = ">=3.8, <3.12"
license = "GPL-3.0-or-later"
authors = [
    { name="Jesús Bautista Villar", email="jesbauti20@gmail.com" }
]

# Required dependencies
dependencies = [
    "numpy>=1.23.5,<1.27",       # safe range, avoids ABI breaks
    "matplotlib>=3.6.1,<3.7",
    "tqdm>=4.64,<5.0",           # tqdm is stable, just avoid 5.x future breakage
    "pandas>=1.5,<2.2",          # 2.x is fine, but cap <2.2 for now
    "scipy>=1.10,<1.11",         # avoids latest refactors (_transition_to_rng removed in 1.11+)
    "ipython>=8.0,<8.16"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests", "examples"]